# Site settings
title: TechCCT
email: hackcct@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official page for TechCCT.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "TechCCT.github.io/" # the base hostname & protocol for your site
twitter_username: TechCCT
github_username:  TechCCT

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  soc_projects:
    output: true
  showcase_projects:
    output: true
  events:
    output: true

